import re


class OCRValidationService:
    """
    Validates and normalizes OCR output for Indian
    vehicle registration numbers.

    Features:
        - Uppercase normalization
        - Whitespace and punctuation removal
        - Indian registration format checks
        - Confidence-based review status
        - Preservation of raw OCR output

    Important:
        This service does not automatically change
        ambiguous characters such as O and 0.
    """

    # Common Indian registration format:
    #
    # KA01MN9787
    # DL01AB1234
    # MH12DE1433
    #
    # Also supports older formats with one-letter
    # series identifiers and optional suffixes.

    REGISTRATION_PATTERN = re.compile(
        r"^[A-Z]{2}[0-9]{1,2}"
        r"[A-Z]{1,3}[0-9]{1,4}$"
    )

    def __init__(
        self,
        minimum_confidence=0.60
    ):
        if not 0.0 <= minimum_confidence <= 1.0:
            raise ValueError(
                "minimum_confidence must be between 0 and 1."
            )

        self.minimum_confidence = (
            minimum_confidence
        )

    @staticmethod
    def normalize_text(text):
        """
        Normalize OCR output without guessing characters.

        Example:
            '(@KA 01 MN 9787)' -> 'KA01MN9787'
        """

        if not isinstance(text, str):
            return ""

        text = text.upper().strip()

        # Keep only letters and digits.
        # Punctuation, spaces, and symbols are removed.
        normalized = re.sub(
            r"[^A-Z0-9]",
            "",
            text
        )

        return normalized

    @classmethod
    def validate_format(cls, text):
        """
        Check whether normalized text matches a
        common Indian registration-number structure.

        This is a structural check, not proof that
        the registration number exists.
        """

        if not text:
            return False

        return bool(
            cls.REGISTRATION_PATTERN.fullmatch(
                text
            )
        )

    def validate(
        self,
        text,
        confidence=0.0
    ):
        """
        Validate an OCR prediction.

        Args:
            text:
                Raw text generated by OCR.

            confidence:
                OCR confidence as a fraction,
                for example 0.82 for 82%.

        Returns:
            Dictionary containing raw text,
            normalized text, format validity,
            confidence, and review status.
        """

        if not isinstance(
            confidence,
            (int, float)
        ):
            raise ValueError(
                "confidence must be numeric."
            )

        if not 0.0 <= confidence <= 1.0:
            raise ValueError(
                "confidence must be between 0 and 1."
            )

        raw_text = (
            text
            if isinstance(text, str)
            else ""
        )

        normalized_text = (
            self.normalize_text(
                raw_text
            )
        )

        format_valid = (
            self.validate_format(
                normalized_text
            )
        )

        if not normalized_text:
            status = "rejected"
            reason = "empty_ocr_output"

        elif not format_valid:
            status = "review_required"
            reason = "invalid_registration_format"

        elif confidence < self.minimum_confidence:
            status = "review_required"
            reason = "low_ocr_confidence"

        else:
            status = "accepted"
            reason = "format_and_confidence_passed"

        return {
            "raw_text": raw_text,
            "normalized_text": normalized_text,
            "format_valid": format_valid,
            "confidence": round(
                float(confidence),
                4
            ),
            "confidence_percent": round(
                float(confidence) * 100,
                2
            ),
            "status": status,
            "reason": reason
        }